LinearmotorVibrator: Update vibration effect
- Above changes because of:
msg: java.lang.NoSuchMethodError: No virtual method setEffectStrength(I)Lcom/oplus/os/WaveformEffect$Builder; in class Lcom/oplus/os/WaveformEffect$Builder; or its super classes (declaration of 'com.oplus.os.WaveformEffect$Builder' appears in /system/framework/framework.jar!classes5.dex)
stacktrace: java.lang.NoSuchMethodError: No virtual method setEffectStrength(I)Lcom/oplus/os/WaveformEffect$Builder; in class Lcom/oplus/os/WaveformEffect$Builder; or its super classes (declaration of 'com.oplus.os.WaveformEffect$Builder' appears in /system/framework/framework.jar!classes5.dex)
	at j5.n$a.handleMessage(VibrateManager.java:105)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)